name: Jorge López
description: Sysadmin, DevOps and code
meta_description: "Jorge López. DevOps, sysadmin, Linux, PHP, coding"

logo: false
paginate: 5
baseurl: /
domain_name: 'jorgelp.com'
permalink: /:year/:month/:title/
plugins: [jekyll-paginate, jekyll-feed]

about: about/
github: https://github.com/adobo/

# Details for the RSS feed generator
url:            'http://jorgelp.com'
author:         'Jorge López Pérez'
email:          'jorge@jorgelp.com'
